<div class="container">
	<div class="row">
		<br>
		<div class="jumbotron">
			<h1 class="display-3">404</h1>
			<hr class="my-4">
			<p class="lead">
				Maybe you're lost<br>
				Maybe the system is lost<br>
				Maybe the world is lost
			</p>
			<p class="lead">
				<a class="btn btn-primary btn-lg" href="<?= $url->get('') ?>" role="button">Home</a>
			</p>
		</div>
		<h1></h1>
		<p>

		</p>
	</div>
</div>