<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<a href="../" class="btn btn-xs btn-info">back</a>&nbsp;&nbsp;&nbsp;<?= $formTitle ?>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-12">
						<?= $this->tag->form($controllerURL."/save") ?>
							<?php foreach ($this->view->form as $element) : ?>
							<div class="form-group">
								<label for="<?=  $element->getName() ?>"><?=  $element->getLabel() ?></label>
								<?= $element ?>

								<?php if ($element->hasMessages()) : ?>
								<p class="help-block">
									<?php foreach ($element->getMessages () as $currentMessage) : ?>
									<?= $currentMessage ?><br>
									<?php endforeach ?>
								</p>
								<?php endif; ?>
							</div>
							<?php endforeach ?>
							<br>
							<input type="submit" class="btn btn-success btn-block" value="Valid">
						</form>
					</div>
					<!-- /.col-lg-6 (nested) -->
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->