<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<a href="<?= $this->url->get(array('for'=>'backend-controller-index', 'controller'=>$this->dispatcher->getControllerName())) ?>" class="btn btn-xs btn-info">back</a>&nbsp;&nbsp;&nbsp;<?= $formTitle ?>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-12">
						<?= $this->tag->form($this->url->get(array('for'=>'backend-controller-save', 'controller'=>$this->dispatcher->getControllerName()))) ?>
							<?php foreach ($this->view->form as $element) : ?>
							<?php if (is_a($element, '\Phalcon\Forms\Element\Hidden')) : ?>
								<?= $element->render() ?>
							<?php else : ?>
							<div class="form-group<?php if ($element->hasMessages()) : ?> has-error<?php endif ?>">
								<label for="<?=  $element->getName() ?>" class="control-label"><?=  $element->getLabel() ?></label>
								<?= $element->render(array('class' => 'form-control')) ?>

								<?php if ($element->hasMessages()) : ?>
								<p class="help-block">
									<?php foreach ($element->getMessages () as $currentMessage) : ?>
									<?= $currentMessage ?><br>
									<?php endforeach ?>
								</p>
								<?php endif; ?>
								<?php if ($this->view->form->hasHelpBlock($element->getName())) : ?>
								<p class="help-block no-message"><?= $this->view->form->getHelpBlock($element->getName()) ?></p>
								<?php endif; ?>
							</div>
							<?php endif; ?>
							<?php endforeach ?>
							<br>
							<input type="submit" class="btn btn-success btn-block" value="Valid">
						</form>
					</div>
					<!-- /.col-lg-6 (nested) -->
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->