<div id="wrapper">

	<!-- Navigation -->
	<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
			        data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?= $this->url->get(array('for'=>'backend-index')) ?>"><?= $this->config->adminTitle ?></a>
		</div>
		<!-- /.navbar-header -->

		<ul class="nav navbar-top-links navbar-right">
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-user">
					<li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
					</li>
					<li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
					</li>
					<li class="divider"></li>
					<li><a href="<?= $this->url->get(array('for'=>'backend-logout')) ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
					</li>
				</ul>
				<!-- /.dropdown-user -->
			</li>
			<!-- /.dropdown -->
		</ul>
		<!-- /.navbar-top-links -->

		<div class="navbar-default sidebar" role="navigation">
			<div class="sidebar-nav navbar-collapse">
				<ul class="nav" id="side-menu">
					<?php foreach (\Phalcon\Di::getDefault()->get('backendService')->getMenu() as $currentMenuLabel=>$currentMenuItem) : ?>
						<?php if ($currentMenuItem->hasSubMenu()) : ?><li>
							<a href="#"><i class="fa fa-<?= $currentMenuItem->getIcon() ?> fa-fw"></i> <?= $currentMenuItem->getLabel() ?><span class="fa arrow"></span></a>
							<ul class="nav nav-second-level">
							<?php foreach ($currentMenuItem->getSubMenuList() as $currentSubMenuLabel=>$currentSubMenuItem) : ?>
								<li><a href="<?= $currentSubMenuItem->getLink()->getURL() ?>"><?= $currentSubMenuItem->getLabel() ?></a></li>
							<?php endforeach; ?>
							</ul>
							<!-- /.nav-second-level -->
							</li>
						<?php else : ?>
						<li>
							<a href="<?= $currentMenuItem->getLink()->getURL() ?>"><i class="fa fa-<?= $currentMenuItem->getIcon() ?> fa-fw"></i> <?= $currentMenuItem->getLabel() ?></a>
						</li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
			<!-- /.sidebar-collapse -->
		</div>
		<!-- /.navbar-static-side -->
	</nav>
	<div id="page-wrapper">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header"><?= $h1 ?></h1>
			</div>
			<!-- /.col-lg-12 -->
		</div>
		<?= $this->flash->output(); ?>
		<?= $this->flashSession->output(); ?>
		<?= $this->getContent(); ?>
	</div>
	<!-- /#page-wrapper -->
	<hr>
	<footer>
		<p>&copy; proGweb 2017</p>
	</footer>
</div>
<!-- /#wrapper -->