<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Please Sign In (<?= $test ?>)</h3>
				</div>
				<div class="panel-body">
					(<?= $titi ?>)
					<form role="form" method="post" action="<?= $url->get('login') ?>">
						<fieldset>
							<div class="form-group">
								<input class="form-control" placeholder="E-mail" name="<?= $config->adminDir ?>-email" type="email" autofocus>
							</div>
							<div class="form-group">
								<input class="form-control" placeholder="Password" name="<?= $config->adminDir ?>-password" type="password" value="">
							</div>
							<div class="checkbox">
								<label>
									<input name="remember" type="checkbox" value="Remember Me">Remember Me
								</label>
							</div>
							<!-- Change this to a button or input when using this as a form -->
							<input type="submit" class="btn btn-lg btn-success btn-block" value="Login">
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>