<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<?= $this->tag->getTitle() ?>

	<!-- Bootstrap Core CSS -->
	<link href="http://res.cloudinary.com/progweb/raw/upload/v1496932879/phalconmerce/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

	<!-- MetisMenu CSS -->
	<link href="http://res.cloudinary.com/progweb/raw/upload/v1496932879/phalconmerce/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="http://res.cloudinary.com/progweb/raw/upload/v1496932879/phalconmerce/dist/css/sb-admin-2.css" rel="stylesheet">

	<!-- Custom Fonts -->
	<link href="http://res.cloudinary.com/progweb/raw/upload/v1496932879/phalconmerce/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>

<?= $this->getContent(); ?>

<!-- jQuery -->
<script src="http://res.cloudinary.com/progweb/raw/upload/v1496932879/phalconmerce/vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="http://res.cloudinary.com/progweb/raw/upload/v1496932879/phalconmerce/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="http://res.cloudinary.com/progweb/raw/upload/v1496932879/phalconmerce/vendor/metisMenu/metisMenu.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="http://res.cloudinary.com/progweb/raw/upload/v1496932879/phalconmerce/dist/js/sb-admin-2.js"></script>

</body>
</html>